
LINK = 'https://github.com/mozilla/geckodriver/releases/download/v0.31.0/geckodriver-v0.31.0-linux64.tar.gz' 

geo: geo/download

# download 
geo/download:
	wget ${LINK}$ 
	tar -xvzf geckodriver* 
	chmod +x geckodriver
	mkdir ./../src/CarStats/drivers
	mv geckodriver ./../src/CarStats/drivers
	rm *.tar.gz

    
